package battle

// lang.go: report templates extracted byte-exact from server/game/lang.php (do not hand-edit).

const (
  tplArmyNumss = "<tr><td  align=\"center\" valign=\"middle\" class=\"TextArmyCount\">%s</td>\r\n                                 <td  align=\"center\" valign=\"middle\" class=\"TextArmyCount\">%s</td>\r\n                                 <td  align=\"center\" valign=\"middle\" class=\"TextArmyCount\">%s</td></tr>"
  tplBadtroopss = "<table border=\"1\" cellpadding=\"0\" cellspacing=\"0\" bordercolor=\"#FFFFFF\" width=\"505\">\r\n      <tr>\r\n    \t<td align=\"center\"  colspan=\"3\" class=\"TitleRedWhite\" ><h4>%s<h4></td>\r\n  \t  </tr>\r\n      <tr>\r\n\t        <td align=\"center\" valign=\"middle\" class=\"TitleBlueWhite\">军队</td>\r\n\t        <td align=\"center\" valign=\"middle\" class=\"TitleBlueWhite\">数量</td>\r\n\t        <td align=\"center\" valign=\"middle\" class=\"TitleBlueWhite\">战斗损失</td>\r\n      </tr>\r\n      %s\r\n    </table>"
  tplBtitles = "<table border=\"1\" cellpadding=\"0\" cellspacing=\"0\" bordercolor=\"#FFFFFF\" width=\"505\">\r\n    <tr>\r\n    \t<td align=\"center\"  colspan=\"4\" class=\"TitleRedWhite\" ><h4>战斗共持续%s回合，我方战斗%s!<h4></td>\r\n  \t</tr>\r\n    <tr>\r\n    <td  class=\"TitleBlueWhite\" width=\"160\">\r\n\t   攻击方(我方)：%s\r\n    </td>\r\n    <td  class=\"WinGreen\" width=\"80\">\r\n\t  <font color=\"#00FF00\">%s</font>\r\n    </td>\r\n    <td class=\"TitleBlueWhite\" width=\"160\">\r\n\t    防守方(敌方)：%s\r\n    </td>\r\n    <td class=\"LoseRed\" width=\"140\">\r\n\t       <font color=\"#CC3333\">%s</font>\r\n    </td>\r\n    </tr>\r\n\t<tr>\r\n\t%s\r\n    </tr>\r\n\t</table>"
  tplYbtitles = "<table border=\"1\" cellpadding=\"0\" cellspacing=\"0\" bordercolor=\"#FFFFFF\" width=\"505\">\r\n    <tr>\r\n    \t<td align=\"center\"  colspan=\"4\" class=\"TitleRedWhite\" ><h4>战斗共持续%s回合，我方战斗%s!<h4></td>\r\n  \t</tr>\r\n    <tr>\r\n    <td  class=\"TitleBlueWhite\" width=\"160\">\r\n\t   攻击方(敌方)：%s\r\n    </td>\r\n    <td  class=\"WinGreen\" width=\"80\">\r\n\t  <font color=\"#00FF00\">%s</font>\r\n    </td>\r\n    <td class=\"TitleBlueWhite\" width=\"160\">\r\n\t    防守方(我方)：%s\r\n    </td>\r\n    <td class=\"LoseRed\" width=\"140\">\r\n\t       <font color=\"#CC3333\">%s</font>\r\n    </td>\r\n    </tr>\r\n\t<tr>\r\n\t%s\r\n    </tr>\r\n\t</table>"
  tplHero = "<td align=\"center\" width=\"80\"><img src=\"/images/herox/hero_%s.jpg\" alt=\"%s\"/><br/><br/></td>\r\n<td >\r\n        <font color=\"#00D8FF\">%s （等级%s）</font>\r\n</td>"
  tplHeroName = "<tr> <td width=\"60\" align=\"center\"><img src=\"/images/herox/hero_%s.jpg\" alt=\"%s\"/> <br/><br/></td>\r\n\t\t\t\t\t\t\t\t        <td><font color=\"#00D8FF\">%s（等级%s）</font></td>\r\n\t\t\t\t\t\t\t\t\t</tr>"
  tplBCount = "<tr>\r\n                                  <td  align=\"center\" valign=\"middle\" >%s</td>\r\n                                  <td  align=\"center\" valign=\"middle\" >%s</td>\r\n                                 </tr>"
  tplResource = "<table width=\"505\" border=\"1\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#FFFFFF\">\r\n                                    <tr> <td colspan=\"5\" align=\"center\" class=\"TitleRedWhite\">%s</td> </tr> \r\n\t\t\t\t\t\t\t\t\t<tr> <td><img src=\"/images/city_gold.png\" width=\"19\" height=\"19\" alt=\"黄金\"/></td> <td><img src=\"/images/resource_food.png\" width=\"19\" height=\"19\" alt=\"粮食\"/></td> <td><img src=\"/images/resource_wood.png\" width=\"19\" height=\"19\" alt=\"木材\"/></td> <td><img src=\"/images/resource_rock.png\" width=\"19\" height=\"19\" alt=\"石料\"/></td> <td><img src=\"/images/resource_iron.png\" width=\"19\" height=\"19\" alt=\"铁锭\"/></td></tr> \r\n\t\t\t\t\t\t\t\t\t<tr><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>\r\n\t\t\t\t\t\t\t\t\t</table>"
  tplTroopback = "<table width=\"505\" border=\"1\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#FFFFFF\">\r\n                                   <tr> \r\n\t\t\t\t\t\t\t\t     <td colspan=\"2\" align=\"center\" class=\"empty2\"><h3>%s</h3></td>\r\n\t\t\t\t\t\t\t\t\t</tr>%s\r\n\t\t\t\t\t\t\t\t   <tr>\r\n\t\t                             <td align=\"center\" valign=\"middle\">军队</td>\r\n\t\t                             <td align=\"center\" valign=\"middle\">数量</td>\r\n                                   </tr>%s\r\n\t\t\t\t\t\t\t\t   </table>"
  tplBsbinfo = "<table width=\"505\" border=\"1\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#FFFFFF\">\r\n                                   <tr> \r\n\t\t\t\t\t\t\t\t     <td colspan=\"2\" align=\"center\" class=\"empty2\"><h3>%s</h3></td>\r\n\t\t\t\t\t\t\t\t\t</tr>\r\n\t\t\t\t\t\t\t\t   <tr>\r\n\t\t                             <td align=\"center\" valign=\"middle\">%s</td>\r\n\t\t                             <td align=\"center\" valign=\"middle\">%s</td>\r\n                                   </tr>%s\r\n\t\t\t\t\t\t\t\t   </table>"
  tplDetect = "<table border=\"1\" cellpadding=\"0\" cellspacing=\"0\" bordercolor=\"#FFFFFF\" width=\"505\">\r\n   \t<tr>\r\n    \t<td align=\"center\" class=\"TitleRedWhite\" ><h3>%s</h3></td>\r\n  \t</tr>"
  tplGet = "<tr><td colspan=\"6\" height=\"25\" class=\"TextArmyCount\">君主声望：%s</td> </tr>\r\n                            <tr> <td colspan=\"6\" height=\"25\" class=\"TextArmyCount\">将领经验：%s</td> </tr>\r\n\t\t\t\t\t\t\t<tr> <td colspan=\"2\" height=\"25\" class=\"TextArmyCount\">伤兵比例：%s％</td> </tr>"
  tplGoods = "<tr> <td colspan=\"6\" height=\"25\" class=\"TextArmyCount\">获得：%s %s</td></tr>"
  tplTitleEnd = "</table>"
  tplWarming = "<tr> <td colspan=\"6\" height=\"25\" class=\"TextArmyCount\">%s</td> </tr>"
  tplEmpty = "<td height=\"55\" bgcolor=\"#17292B\" class=\"TitleListWhite\"> <table width=\"255\" border=\"0\" align=\"center\" cellspacing=\"0\" bgcolor=\"#17292B\"> </table>"
  tplEnd = "军队%s%s。<br/>"
  tplTitle = "向%s执行%s任务的军队%s。<br/>"
  tplTitle1 = "一支军队向%s进行了%s。<br/>"
  tplYouend = "<br/>你可以使用道具，提升将领和军队的作战能力，使他们能更有效的消灭敌人。<br/>“虎符”增加将领的统率，“武曲星符”增加将领的攻击，“智多星符”增加将领的防御，<br/>“青囊书”增加军队伤兵的恢复数量，“陷阵战鼓”增加军队攻击力，“八卦阵图”增加军队防御力。<br/>战后别忘记到“校场”的“伤兵营”恢复伤兵。安抚百姓可以恢复民心、降低民怨，使用“安民告示”可以立即将民心全部恢复。<br/>建造仓库可以减少被掠夺的资源。如果敌军太强大，你可以选择不出战，避免军队损失。<br/> 使用“免战牌”避免被攻击，使用“迁城令”远离你的敌人。"
  tplInvade = "&nbsp;目标城池民心%s-%s=%s。<br/>&nbsp;民怨%s+%s=%s。<br/>&nbsp;占领该城池需要该城池民心达到0，当前民心为%s。（%s）"
  tplJueweiInv = "<br/>&nbsp;统治新的城池需要爵位达到 %s，我方君主爵位为 %s。（%s）<br/>"
  tplCityInv = "&nbsp;该治下共有%s座%s，占领该城池需本盟至少拥有其三分之一的%s，我方联盟共拥有%s座。（%s）<br/>"
  tplLostHero = " <tr> <td colspan=\"2\" height=\"25\" class=\"TextArmyCount\">%s 等级( %s ) 突围而去！</td> </tr>"
  tplNone = "大军压境之下，敌人落荒而逃，未发生任何战斗！<br/>只有当你派出更少的军队时对方才愿意和你战斗。"
  tplCatchHero = "<tr> <td colspan=\"6\" height=\"25\" class=\"TextArmyCount\">%s 等级( %s ) 被俘虏了！</td> </tr>"
)
